### ISSUE TITLE
[Feature Request] Export all G-code together.

### ISSUE THREAD

**Issue by sblite** [mkrabset/krabzcam#13]
Love the application. Im using it with a maslow, Is there a way to export all the G-codes you've created together?

**Comment by geobruce** [comment]
I was planning to request this also.
An option to combine toolpaths if they use the same tool.

**Comment by mkrabset** [comment]
Hi, thanks for your input!
I've added support for exporting gcode for multiple toolpaths.
Please test it and let me know of any issues.

**Comment by geobruce** [comment]
Tested and works perfectly!
