### ISSUE TITLE
[Feature request] Other Pocket paterns 

### ISSUE THREAD

**Issue by geobruce** [mkrabset/krabzcam#15]
Last weekend I played around with a pen holder on my CNC. and I tried using krabzCam for generating g-code. For drawing = engraving lines it's perfect. But for filling (=pocketing, I guess) the drawing it works kind of.  
![image](https://user-images.githubusercontent.com/4906120/128896909-84cc0296-090a-4f71-a831-1a4a34b746d5.png)
![image](https://user-images.githubusercontent.com/4906120/128896979-8da778cb-19b8-4c75-9823-c410b79204f3.png)

It would be cool that the pocket feature would have other strategies as well like:
Line:
![image](https://user-images.githubusercontent.com/4906120/128898265-e767fb7d-47ed-4b3b-afc7-9ff2b6a0e447.png)
Trianagle:
![image](https://user-images.githubusercontent.com/4906120/128898392-091739ee-6e16-4ba7-a2e5-5de552184523.png)
Grid: = cross hatch

This might go two ways:
1. extended clearing strategies for pocketing
2. extended clearing strategies for pocketing + new specific operations for plotters
With a few nice features like cross hatching, hatching, ... this can go quite far: 
![image](https://user-images.githubusercontent.com/4906120/128899123-03529d5c-971e-4715-a02c-c7205b20c2f7.png)

Please let me know what you think.

Kind regards
Bruce

**Comment by mkrabset** [comment]
Hi, yes the pocketing toolpaths aren't optimal for plotter use.
I guess it would be possible to fill shapes using the 'RELIEF_FOLLOW'-operation, but this would be cumbersome and would also involve converting the svg to an image.

I'm thinking about something like:
* Adding a pattern attribute to the pocket operation, with 'DEFAULT' and 'LINE' as selectable values (dropdown).
* When selected pattern is 'LINE', show an additional 'angle' attribute.

...so in order to achieve the 'triangle'-pattern (above), you create 3 identical 'LINE'-toolpaths with angles 0, 60 and 120 deg.

It may also make sense to have an option for 'uni-directional', to always cut in the same direction instead of back and forth.

In addition to plotter usage, I think this could also be useful for surfacing operations.

What do you think?

**Comment by geobruce** [comment]
> 
> I'm thinking about something like:
> 
>     * Adding a pattern attribute to the pocket operation, with 'DEFAULT' and 'LINE' as selectable values (dropdown).
> 
>     * When selected pattern is 'LINE', show an additional 'angle' attribute.
> 
> 
> ...so in order to achieve the 'triangle'-pattern (above), you create 3 identical 'LINE'-toolpaths with angles 0, 60 and 120 deg.
> 
> It may also make sense to have an option for 'uni-directional', to always cut in the same direction instead of back and forth.
> 
> In addition to plotter usage, I think this could also be useful for surfacing operations.
> 
> What do you think?

This sounds very interesting! I'll can do some tests if the feature is there ;)


> I guess it would be possible to fill shapes using the 'RELIEF_FOLLOW'-operation, but this would be cumbersome and would also involve converting the svg to an image.
> 

I've never tried this feature before what kind of image does it expect?

**Comment by mkrabset** [comment]
The RELIEF_FOLLOW-operation uses a grayscale-image as height-map and moves the tool over the 'terrain'.
...like [this](https://www.flickr.com/photos/25948865@N03/49711856193/), creating [this](https://www.flickr.com/photos/25948865@N03/49712388746/) result.

With a black and white image and some gcode editing I guess you could achieve back-and-forth strokes with a pen...but as I said..it would be a bit cumbersome.

I will try to create LINE support for pocket-operation as described...but it will take some time. I'll let you know.

**Comment by geobruce** [comment]
Thanks in advance !!

**Comment by mkrabset** [comment]
Hi again. 
I've added support for 'line-pockets' in the latest version. (Hopefully without breaking anything)
Please try it out and let me know of any issues.

-Marius

**Comment by geobruce** [comment]
I wasn't able to test this on the machine but in the browser it's looking good! Thanks for that.
Is there already a functionality to set the lines at a certain angle, because I couldn't find that.

Thanks for your effort keeping on improving the features!

**Comment by mkrabset** [comment]
Hi, when you select pattern='Line', a few additional parameters should become visible..
* LineAngle
* LineDirection

![image](https://user-images.githubusercontent.com/885864/131465370-d3e75003-0d37-4fb9-a125-ea946cefb110.png)

Use of 'optimize' also seems to be useful.

-Marius

**Comment by geobruce** [comment]
strange I didn't see it the first time maybe my version wasn't refreshed.

Thanks for adding this, it looks good I'll test this when I've time.

**Comment by mkrabset** [comment]
Did some testing myself as well 🙂
Drew this little guy on my plotter.
Had to do some gcode editing though, since my plotter is using m5/m3 for pen up/down.

![image](https://user-images.githubusercontent.com/885864/131743916-1320a4c0-0423-4da4-86d7-4660afd78f54.png)
