### ISSUE TITLE
SVG parsing issue

### ISSUE THREAD

**Issue by risacher** [mkrabset/krabzcam#19]
[krabzcam-parse-example.svg.gz](https://github.com/mkrabset/krabzcam/files/7349751/krabzcam-parse-example.svg.gz)
 
For unknown reasons, when the attached file is loaded into Krabzcam, one of the "soot sprites" is in the wrong place.  Ungzip the attached file, and compare it in Inkscape vs Krabzcam.

**Comment by mkrabset** [comment]
Thank you for reporting!
Should be fixed now.
-Marius
