### ISSUE TITLE
Feature request: drag knife corner actions

### ISSUE THREAD

**Issue by risacher** [mkrabset/krabzcam#2]
I'd like to use KrabzCAM for a drag knife (I use a CB09/CB09U Graphtec Blade Holder in a CNC engraver).  

Since the cutting tip of a drag knife literally drags behind the center of motion, compensating actions need to be made to either close paths or square corners.  I believe these are generally called "corner actions".  

As a reference, Donek Tools offers a free gcode processor to add corner actions, but it's implemented as Excel macros.  (ugh) https://donektools.com/free-cnc-router-software/#corner-actions

**Comment by mkrabset** [comment]
Thanks for the input!
I'll see what I can come up with, but no promises.
 
Currently I'm thinking something like a follow-path operation, but with parameters:
- dragOffset  (How far behind center is the tip of the knife)
- cutDepth  (Depth when cutting)
- swivelDepth (Depth when swiveling)
- feedRate
- plungeRate
- minSwivelAngle (Minimum turn angle for doing the 'corner action')

I guess for multiple path operations I will need to assume that the tool-angle is preserved during rapid moves.
Does this sound reasonable? (I don't have any experience with drag-knives)

**Comment by mkrabset** [comment]
I've added a new operation type for drag knife. 
Please try it out. 
Feedback is appreciated.

**Comment by risacher** [comment]
First, you are amazing, and I'm very impressed both with the drag_knife operation and with krabzcam in general.

I think the assumption that the tool-angle is preserved during rapid moves is a good assumption - it the only reasonable assumption.  There are machines called "tangent knives" that actually use the A axis to set the blade direction, but I ain't got one o' those.

Minor bug: Any "g1 z0" moves are specified as "g1 z0 fnan", which breaks the gcode.  I did a find-replace of "fnan" for "f100" in the gcode, and its running like a champ on my sainsmart genmitsu right now.

**Comment by mkrabset** [comment]
Thanks for your nice words!
I made my own little 3d-printed dragknife to test it out. 
A bit tricky to set up, but quite interesting to see it in action.
 
The "g1 z0 fnan" bug should be fixed now.
Happy cutting!

**Comment by risacher** [comment]
The actual result of my first cut with the dragknife operation came out well, but the path it cuts seems surprisingly jerky around curves, as if it's constantly over-correcting?  Is this expected?

![Screenshot from 2021-02-02 10-27-04](https://user-images.githubusercontent.com/632426/106622355-7d09b580-6541-11eb-9999-ee090ae2d312.png)

**Comment by mkrabset** [comment]
I would say this is expected.
There is quite a bit of math involved. :-)
Typically we start with a bezier curve, which is converted into a sequence of circular arc-segments and lines, given a tolerance limit for error.
(You can toggle showing these arcs by pressing 'c' while in the 2d viewport)
This interpolation often causes a tiny shift in direction when going from one segment to the next. This shift gets amplified by the tool-offset, causing these seemingly big adjustments in direction.

I'm not sure how best to achieve this, but I guess the more circular and smooth these bends are, the less adjustments required.
 
As you can see below, it is possible to join two circular segments with different radiuses without getting any adjustment at all.
![bilde](https://user-images.githubusercontent.com/885864/106656117-8a06c300-659a-11eb-8f6e-7e090a6f28c3.png)


It might help opening your SVG in inkscape and remove unnecessary path-nodes, or use the 'simplify path' feature.
(You can play with 'simplification threshold' in Edit / Preferences / Behaviour)

Hope this is helpful.

**Comment by risacher** [comment]
I used this again for a different project and didn't see any of this jaggy-ness.  

Attached is the first cut I did with the KrabzCAM drag knife feature. (Logo of my son's hockey team)

![KrabzCAM-drag-knife](https://user-images.githubusercontent.com/632426/107130146-ca1abe00-6898-11eb-98c9-21b8ab11893c.jpg)
