### ISSUE TITLE
[question] does "optimize" break assumptions about drag knife orientation?

### ISSUE THREAD

**Issue by risacher** [mkrabset/krabzcam#24]
In the comments on #2 you indicated that you assumed that the drag knife would stay in the same orientation during fast moves (which I think is right.).  But the "optimize" button re-orders all the fast moves... so maybe the assumptions about blade orientation are wrong after a fast move if it's been optimized.  Does the "optimize" function re-compute the drag knife corner actions while it is optimizing the fast moves?

**Comment by mkrabset** [comment]
Hi, as far as I can see, the corner-actions are updated correctly after optimization. 
Have you had any problems with this?
