### ISSUE TITLE
[Feature request] Select paths by color

### ISSUE THREAD

**Issue by risacher** [mkrabset/krabzcam#28]
I usually generate SVG files as input to Krabzcam in Inkscape.  I think it would be useful to be able to select paths by color in Krabzcam so that I can indicate in Inkscape that different parts are intended for the same operation.  For example, in Inkscape, I might put all the *dark* laser engraves in blue, and all the *light* engraves in red.  Or similar for different CNC depths, whatever.

**Comment by risacher** [comment]
Awesome.  Thanks for this.  Closing.

**Comment by risacher** [comment]
Found a use case where this is not working properly.  It seems to select closed paths separately from open paths..?  See linked example and try to use Shift-A to select the text (which is all one color) [cat tag](https://risacher.org/moriko-35mm.svg). At least for me, this will select the 'o', '0', and the dot on the 'i' separately from the other letters.

**Comment by davi-domo** [comment]
hello
have you tried with a smaller cutter diameter?
this has already happened to me if the cutter is larger than the surface to be removed

**Comment by mkrabset** [comment]
I've added a fix for the closed vs. open path problem. 
Please test it, and let me know of any problems.

**Comment by risacher** [comment]
As it turns out, I had to re-make the part where I found this bug.  The fix worked great.  Thanks and closing.

**Comment by risacher** [comment]
@davi-domo When I found the bug, I was using it for laser engraving, so the cutter size is not relevant.
