### ISSUE TITLE
Bug in dog-bone feature.

### ISSUE THREAD

**Issue by geobruce** [mkrabset/krabzcam#32]
I'm trying to use the dog-bone feature and I discovered an issue.

outside profile: (no dog-bones are generated) (project attached)
[profile outside.json.gz](https://github.com/mkrabset/krabzcam/files/9709869/profile.outside.json.gz)
![image](https://user-images.githubusercontent.com/4906120/193904735-67041134-174c-4dc4-bd47-e1809fac3896.png)

profile outside inconsistent behavior: [outside inconsistent.json.gz](https://github.com/mkrabset/krabzcam/files/9709926/outside.inconsistent.json.gz)
![image](https://user-images.githubusercontent.com/4906120/193906539-0fe70f9a-bbb6-443c-980d-467a715d4f89.png)

Profile inside [dia = 10mm] (no dog-bones are generated) [prof-inside-10mm.json.gz](https://github.com/mkrabset/krabzcam/files/9709927/prof-inside-10mm.json.gz)
![image](https://user-images.githubusercontent.com/4906120/193905752-d485c18d-e5ca-4b5e-be44-1fb7429cf623.png)

 Profile inside [dia = 1mm] (dog-bones are generated) with the default diameter it works)
![image](https://user-images.githubusercontent.com/4906120/193905982-44cdf6d4-2422-4102-8457-9602689a5641.png)

![dogbone test](https://user-images.githubusercontent.com/4906120/193904896-e53317ad-4b10-4b14-8e9b-b39afc253266.svg)
[dogbone test.zip](https://github.com/mkrabset/krabzcam/files/9709876/dogbone.test.zip)

Can you please have a look at this?
Do you might know a work around or a quick fix?
I'm taking a day off soon to have some time with the CNC machine I'm planning on making this: 
![image](https://user-images.githubusercontent.com/4906120/193907278-c9b147b6-cb20-4568-92d0-889a109bbdae.png)
I included a part of the design file I plan on cutting out. So you can test this. I'm planning on using a 8mm and 3.175mm router bit.
[extensive test file v0.1a.zip](https://github.com/mkrabset/krabzcam/files/9709954/extensive.test.file.v0.1a.zip)

Thanks in advance and keep up the good work!

_Originally posted by @geobruce in https://github.com/mkrabset/krabzcam/issues/12#issuecomment-1267477843_

**Comment by mkrabset** [comment]
Hi, thanks for reporting!
I've added some fixes. Please do some testing and let me know of any issues.

-Marius

**Comment by geobruce** [comment]
Last night I noticed there was an update so I generated the gcode and all seems to work fine for the moment.

Thanks for the quick fix!

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
