### ISSUE TITLE
Dogbones fail on hexagon or higher n-gon.

### ISSUE THREAD

**Issue by jeffs555** [mkrabset/krabzcam#36]
The dogbone feature is really nice, but it fails if more than 5 inside angles. You can see it by placing an n-gon and doing an inside profile with dogbones enabled. N-gons with 3,4,5 sides work fine and have dogbones in all corners. Hexagon only puts dogbones in 3 corners. If more than 6 sides, then no dogbones are done.

**Comment by mkrabset** [comment]
Thanks for your input!
There is a hardcoded maximum angle for dogbones.
I've increased the value from 120 deg to 170 deg. 
Guess I might make this configurable some time in the future.

**Comment by jeffs555** [comment]
Thanks, that explains everything I was seeing. I just noticed it because I wanted to do dogbones inside a hex and that change does it. 
Did some playing with triangles and it looks like there is also a minimum angle of around 40 degrees. Don't know if anyone would ever need less than that. 
Thanks again.
