### ISSUE TITLE
Initial position

### ISSUE THREAD

**Issue by Sodisplays** [mkrabset/krabzcam#39]
Hi, congrats for the nice job!

I need to know after I create a GCode file, where I need to setup my CNC initial point, 
Upper Letf,
Upper right
Centre
Bottom Letf ou Bottom right?

Camotics simulates fin down-letf side and NCviewer from upper left...

Thanks alot

**Comment by mkrabset** [comment]
Hi, thanks!

The xy-coordinates you get in the generated gcode are same as you see on the user interface. 

So, if your machine is zeroed at the bottom left, then you would place your svg object like this:

![image](https://github.com/mkrabset/krabzcam/assets/885864/1ebe50e3-d934-439a-b43a-5c40f1109c39)


In NCViewer this would like like this:
![image](https://github.com/mkrabset/krabzcam/assets/885864/4cfa9d7d-30d8-42eb-883e-74c8a6633d43)


...and in Camotics (at least my version):
![image](https://github.com/mkrabset/krabzcam/assets/885864/273f896b-e810-40cb-90b6-8bd2394b37a7)




(I hope this makes sense 🙂 ) 

-M

**Comment by Sodisplays** [comment]
Hi,

Thank you very much, it worked fine...

Regards
Alexandre

Enviado via Proton Mail para dispositivos móveis

-------- Mensagem Original --------
Em 4 de out de 2023 13:18, Marius Krabset escreveu:
