### ISSUE TITLE
[Feature request] - window close confirmation

### ISSUE THREAD

**Issue by davi-domo** [mkrabset/krabzcam#41]
hi marius
Is it possible to integrate a confirmation of closing the krabzcam window
so as not to forget to save the current project
good luck and I still love KRABZCAM

**Comment by mkrabset** [comment]
Thanks for the suggestion David. 
I've just added a simple solution for this. It can be enabled in the "settings" dialog.
Just check off "Confirm on close" and hit "ok". 
Then it should ask for confirmation before closing or reloading app. 
I've only tested it in firefox and chrome...seems to work fine with those...

![image](https://github.com/mkrabset/krabzcam/assets/885864/96657afb-2271-4588-b41d-645081ad0147)

I haven't bothered to check for unsaved changes, so it will ask for confirmation regardless of this..maybe something for later :-)

Please let me know of any issues

**Comment by dadoprom** [comment]
Ok, this one was very much needed, thank you :)

**Comment by davi-domo** [comment]
Thanks Marius 
It’s really cool and she’s responsive
I’m gonna tell my community
Thanks
