### ISSUE TITLE
reverse cleanup bug

### ISSUE THREAD

**Issue by davi-domo** [mkrabset/krabzcam#45]
Hi
I met a bug recently with the cleanups
the pocket is ok but the cleanups are done outside
here are some captures that will be more meaningful
<img width="640" alt="Capture_decran_2024-03-18_a_17 35 06" src="https://github.com/mkrabset/krabzcam/assets/19379465/aa012bcd-74fa-4450-b0f2-b2f273d1843b">
<img width="640" alt="Capture_decran_2024-03-18_a_17 35 46" src="https://github.com/mkrabset/krabzcam/assets/19379465/c246c549-73c5-4884-8b02-0acc75c8ecfb">

**Comment by mkrabset** [comment]
Hmm, that's strange. 
Maybe it gets confused about what objects are inside of what objects. 
Seems like one of the object is touching the outer rectangle.
Will it improve if you move the inner parts a tiny bit to the right?

**Comment by davi-domo** [comment]
Hi
  I tried with an old project where it worked well, and I found the same problem,
it seems to me that it reverses the path selection

here is the original pocket
![image](https://github.com/mkrabset/krabzcam/assets/19379465/aaf030da-a3c8-4874-9a5c-db708fc383c4)

here the cleanup done at the time of the project
![image](https://github.com/mkrabset/krabzcam/assets/19379465/5e6059f9-f1b8-4b0a-b7cd-a57080296183)

and there the cleanup that I just did again, as we see he did the cleanup on the inside of the lettering
![image](https://github.com/mkrabset/krabzcam/assets/19379465/88901cc4-c13b-444f-b138-5589715bb9ae)

it's a project that I had saved where everything had worked well
but now it reverses the selections

**Comment by mkrabset** [comment]
Thanks for reporting David!
Should be fixed now.

**Comment by davi-domo** [comment]
Hello marius
it's perfect I just tried it again
THANKS
