### ISSUE TITLE
Unwanted tool paths

### ISSUE THREAD

**Issue by CycloRetro** [mkrabset/krabzcam#47]
when doing a simple pocket for a basic shape the software adds in these extra tool paths which are not needed, please fix. 6 months ago it was working better, go back to the old version please.
![Screen Shot 2024-06-18 at 11 49 36 am](https://github.com/mkrabset/krabzcam/assets/89329897/b94442f2-f188-4d54-bd85-03a4b0ecedbf)

**Comment by mkrabset** [comment]
If you want to run an older version, you can clone the repo, checkout the version you want, and run it offline.
