### ISSUE TITLE
How to delete Tabs?

### ISSUE THREAD

**Issue by JasonKleban** [mkrabset/krabzcam#48]
If I use the Tab tool to add a Tab, but I realize it is a mistake, how can I remove it or undo it?

Thanks!

**Comment by mkrabset** [comment]
I've just added support for removing existing tabs. 
Just hold down 'shift' after pressing 't', then point to existing tab and delete with mouse button.

I should have added this a long time ago..thanks for the reminder!

Please test and let me know if you run into any issues.
