### ISSUE TITLE
How to reorder tool paths?

### ISSUE THREAD

**Issue by JasonKleban** [mkrabset/krabzcam#49]
I am manually creating a Relief layered toolpath with different depths of cut of the workpiece.  I haven't actually built/cut anything for real on a CNC, but if I want all the toolpaths to be in one gcode, I assume I need to order the toolpaths.  I don't see how to reorder without deleting and recreating in the correct order.

Thanks!

**Comment by JasonKleban** [comment]
Oh, I see this seems to be available when saving g-code:

![image](https://github.com/mkrabset/krabzcam/assets/17498172/8c300b9b-e6c1-49ba-9a56-e216c258baf3)

**Comment by mkrabset** [comment]
Yes, that's the way :-)
