### ISSUE TITLE
Unable to cut a slot narrower than 2x tool for Pocket?

### ISSUE THREAD

**Issue by JasonKleban** [mkrabset/krabzcam#50]
If I have a closed path that is at least .25in wide, and a tool that is .25in wide, no toolpath seems to be generated (or, at least, drawn).  If I drop the tool size to less than 1/2 of the cut width, the tool path is generated.

![image](https://github.com/mkrabset/krabzcam/assets/17498172/1ff05797-3a62-44bf-89ae-0ce4170072c5)

(Here I'm trying to clear away about 1/4in of material at half depth of the material)

**Comment by mkrabset** [comment]
Hmm, you should be able to process all places where the tool fits. (You might need a tiny margin though)

I'm having a hard time making sense of your screenshot. 
Maybe you could try simplifying it by removing paths not involved in the operation in question ? (e.g. the unselected paths)
