### ISSUE TITLE
[feature request] Rest machining

### ISSUE THREAD

**Issue by geobruce** [mkrabset/krabzcam#9]
It would be nice to have a feature where you could do a pocket or any operation. With a rough large diameter bit first and only cleanup the left overs with a smaller diameter bit. This is useful for large operations with only a little text or details that must be kept. You can see an example of this functionality in [Easel](https://easel.inventables.com/users/sign_in) it is not opensource and you do need a free account. But I prefer to support open source software.

In your preview in krabzCam it's easy to see what material will be left over as the bit can't go there. Maybe it's not too much work for you to add this useful feature that will save many people much time.

**Comment by mkrabset** [comment]
Hi, yes this would be a nice time-saver.
I will do some thinking. Probably a lot of complexity here..

**Comment by mkrabset** [comment]
I've added rest-machinging functionality to the 'add cleanup'-button. This button can now be used for both v-bit toolpaths and profiles/pockets.

Please check it out and let me know of any issues.
![image](https://user-images.githubusercontent.com/885864/120893654-b1d36980-c614-11eb-8ca6-c08eea00a0f1.png)

**Comment by geobruce** [comment]
This looks fantastic! Thank you very much!!
